### ISSUE TITLE
Logica en vistas

### ISSUE THREAD

**Issue by farojos** [plorrego/noticiero#1]
Esto debe estar en el modelo
https://github.com/plorrego/noticiero/blob/65f7ddcb3b39f517395486b89bcd602daaf0a02b/app/views/class_news/index.html.erb#L35

**Comment by plorrego** [comment]
Hola Felpe,
Como se puede implementar esto desde el modelo?

**Comment by farojos** [comment]
en el modelo
```
def truncar
  self.body=self.body[0..500]
end
```
